"use client";

/**
 * The send-to-client email, drafted from the package and editable before it goes.
 *
 * Deliberately NOT generated by the model. The draft is a template filled from the run
 * record, which means it opens instantly, costs no tokens, cannot quote a price the
 * optimizer did not produce, and never leaks the internal pricing rationale. The rep edits
 * it — they know the client and we do not.
 *
 * The tone target is a short sell: what they get, what it costs, one reason to say yes, one
 * ask. Anything longer gets skimmed, and the numbers are the argument.
 */

import { useEffect, useMemo, useRef, useState } from "react";

import { CheckIcon } from "@/components/ui/Icon";
import {
  type PackageMetrics,
  flightEndDate,
  packageLineRows,
  packagePlaces,
} from "@/lib/derive";
import { formatCurrency, formatDate, formatNumber } from "@/lib/format";
import type { CampaignSpec, OptimizedPackage, ScreenCandidate } from "@/lib/types";

export function EmailDialog({
  pkg,
  spec,
  candidates,
  metrics,
  title,
  onClose,
}: {
  pkg: OptimizedPackage;
  spec: CampaignSpec;
  candidates: ScreenCandidate[];
  metrics: PackageMetrics;
  title: string;
  onClose: () => void;
}) {
  const draft = useMemo(
    () => composeEmail({ pkg, spec, candidates, metrics, title }),
    [pkg, spec, candidates, metrics, title],
  );

  const [subject, setSubject] = useState(draft.subject);
  const [body, setBody] = useState(draft.body);
  const [copied, setCopied] = useState(false);
  const bodyRef = useRef<HTMLTextAreaElement>(null);

  // Escape closes, and focus lands in the body — the rep almost always edits the greeting
  // first, so that is where the caret belongs.
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    bodyRef.current?.focus();
    bodyRef.current?.setSelectionRange(0, 0);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  async function copyAll() {
    try {
      await navigator.clipboard.writeText(`Subject: ${subject}\n\n${body}`);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1800);
    } catch {
      // Clipboard is permission-gated and blocked outside a secure context. The textarea
      // is right there, so a failed copy is a non-event rather than an error to report.
      bodyRef.current?.select();
    }
  }

  function openInMailClient() {
    // No recipient: the rep picks it in their own client, which also keeps client
    // addresses out of this app entirely.
    const href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = href;
  }

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label="Send proposal email"
      className="fixed inset-0 z-50 flex items-center justify-center bg-zinc-900/40 p-6"
      onClick={onClose}
    >
      <div
        className="flex max-h-[85vh] w-full max-w-2xl flex-col overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-lg"
        onClick={(event) => event.stopPropagation()}
      >
        <header className="flex items-baseline justify-between gap-4 border-b border-zinc-100 px-5 py-3">
          <div>
            <h2 className="text-[13px] font-semibold text-zinc-900">Send to client</h2>
            <p className="text-[11px] text-zinc-500">
              Drafted from the package. Edit anything before you send it.
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="cursor-pointer text-[11px] font-semibold text-zinc-400 hover:text-zinc-700"
          >
            Close
          </button>
        </header>

        <div className="flex-1 space-y-3 overflow-y-auto px-5 py-4">
          <label className="block space-y-1">
            <span className="text-[10px] font-bold tracking-wider text-zinc-400 uppercase">
              Subject
            </span>
            <input
              type="text"
              value={subject}
              onChange={(event) => setSubject(event.target.value)}
              className="w-full rounded-lg border border-zinc-200 px-3 py-2 text-xs text-zinc-800 focus:border-violet-500 focus:outline-none"
            />
          </label>

          <label className="block space-y-1">
            <span className="text-[10px] font-bold tracking-wider text-zinc-400 uppercase">
              Message
            </span>
            <textarea
              ref={bodyRef}
              value={body}
              onChange={(event) => setBody(event.target.value)}
              rows={18}
              className="w-full resize-y rounded-lg border border-zinc-200 px-3 py-2 font-sans text-xs leading-relaxed text-zinc-800 focus:border-violet-500 focus:outline-none"
            />
          </label>
        </div>

        <footer className="flex flex-wrap items-center justify-between gap-2 border-t border-zinc-100 bg-zinc-50/70 px-5 py-3">
          <span className="text-[10px] text-zinc-400">
            Attach the exported PDF in your mail client.
          </span>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={copyAll}
              className="flex cursor-pointer items-center gap-1.5 rounded-lg border border-zinc-200 bg-white px-3 py-1.5 text-[11px] font-semibold text-zinc-700 hover:bg-zinc-50"
            >
              {copied ? <CheckIcon className="h-3 w-3 text-emerald-600" /> : null}
              {copied ? "Copied" : "Copy"}
            </button>
            <button
              type="button"
              onClick={openInMailClient}
              className="cursor-pointer rounded-lg bg-violet-950 px-3.5 py-1.5 text-[11px] font-semibold text-zinc-50 shadow-xs hover:bg-violet-900"
            >
              Open in mail client
            </button>
          </div>
        </footer>
      </div>
    </div>
  );
}

// ------------------------------------------------------------------- the draft

interface EmailDraft {
  subject: string;
  body: string;
}

/**
 * A short sell built from the package's own figures.
 *
 * Client-safe by construction: reach, views, frequency, locations, flight, total. No price
 * band, no occupancy, no scores, no solver. The one persuasive line is the cost per
 * thousand views, because it is the number a media buyer actually compares on.
 */
function composeEmail({
  pkg,
  spec,
  candidates,
  metrics,
  title,
}: {
  pkg: OptimizedPackage;
  spec: CampaignSpec;
  candidates: ScreenCandidate[];
  metrics: PackageMetrics;
  title: string;
}): EmailDraft {
  const rows = packageLineRows(pkg, candidates);
  const places = packagePlaces(rows);
  const where = places.length === 0 ? "the network" : joinWords(places);
  const start = formatDate(spec.start_date);
  const end = formatDate(flightEndDate(spec.start_date, spec.duration_days));

  const formats =
    metrics.screenTypeBreakdown.length > 0
      ? joinWords(
          metrics.screenTypeBreakdown.map(
            (t) =>
              `${t.count} ${t.label.split("_").join(" ")} ${t.count === 1 ? "screen" : "screens"}`,
          ),
        )
      : `${metrics.screenCount} ${metrics.screenCount === 1 ? "screen" : "screens"}`;

  const lines = [
    "Hi there,",
    "",
    `Following up on ${title} — here is what we can put together for you.`,
    "",
    `We would run across ${where} for ${spec.duration_days} days, ${start} to ${end}, on ${formats}.`,
    "",
    `That puts your message in front of ${formatNumber(metrics.expectedReach)} people, ` +
      `with ${formatNumber(metrics.grossImpressionsViewed)} total views across the flight — ` +
      `so the average person sees it ${metrics.expectedFrequency.toFixed(0)} times rather than once and forgetting it.`,
    "",
    `Total investment: ${formatCurrency(metrics.totalCost, 2)}.`,
  ];

  if (metrics.effectiveCpm !== null) {
    lines.push(
      `That works out to ${formatCurrency(metrics.effectiveCpm, 2)} per thousand views.`,
    );
  }

  lines.push(
    "",
    "The full schedule of screens and rates is attached. These are live placements, so " +
      "availability moves — happy to hold them while you take a look.",
    "",
    "Would a short call this week work to walk through it?",
    "",
    "Best regards,",
  );

  return {
    subject: `${title} — ${metrics.screenCount} screens, ${start} to ${end}`,
    body: lines.join("\n"),
  };
}

/** "A, B and C" — an Oxford-comma-free list for prose. */
function joinWords(items: string[]): string {
  if (items.length === 0) return "";
  if (items.length === 1) return items[0];
  return `${items.slice(0, -1).join(", ")} and ${items[items.length - 1]}`;
}
